apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "remediation"
spec:
  stages:
    - name: "production"
      sequences:
      - name: "remediation"
        tasks:
          - name: keptn-intelligent-scaleup
      # - name: "scaling"
      #   triggeredOn:
      #     - event: "production.remediation.finished"
      #       selector:
      #         match:
      #           classification.type: "real_user"
      #     - event: "production.scaling.finished"
      #       selector:
      #         match:
      #           evaluation.result: "fail"
      #   tasks: 
      #     - name: scaling
      #     - name: evaluation
      #       triggeredAfter: "2m"
      #     - name: ticketing
      # - name: "prevention"
      #   triggeredOn:
      #   - event: "production.remediation.finished"
      #     selector:
      #       match:
      #         classification.type: "synthetic"
      #   tasks: 
      #     - name: blocking
      #     - name: ticketing

      # - name: "notify"
      #   triggeredOn:
      #     - event: "production.scalling.finished"
      #     - event: "production.prevention.finished"
      #   tasks:
      #     - name: notify